/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.io.File;
import java.util.Arrays;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author Student
 */
public class CuvantFrame extends javax.swing.JFrame {

    /**
     * Creates new form CuvantFrame
     */
    public CuvantFrame() {
        initComponents();
        
        setLocationRelativeTo(null);
        setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Cuvant:");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Baga o fisa bosulica");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1))
                .addGap(61, 61, 61)
                .addComponent(jButton1)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            int nrTranz,nrStari,nrStariFinale,nrCuvAlfabet;
            
            File fin = new File("date.txt");
            Scanner s = new Scanner(fin);
            
            nrStari = s.nextInt();
            nrCuvAlfabet = s.nextInt();
            nrStariFinale = s.nextInt();
            nrTranz = s.nextInt();
            
            Dfa aparat = new Dfa(new int[nrStari],new int[nrStari][nrCuvAlfabet],new int[nrStariFinale],nrStari,nrCuvAlfabet,nrStariFinale);
            for (int i=0;i<aparat.getNrStari();i++){
                aparat.getStari()[i]=s.nextInt();
            }
            
            s.nextLine();
            String st = s.nextLine();
            st = st.replaceAll("\\s+","");
            char[] c = st.toCharArray();
            aparat.setAlfabet(c);
            aparat.setStareInit(s.nextInt());
            
            for (int i=0;i<aparat.getNrStariFinale();i++){
                aparat.getStariFinale()[i]=s.nextInt();
            }
            
            
            //Arrays.fill(aparat.getTranzitii(),-1);
            for (int i=0;i<nrStari;i++){
                for (int j=0;j<nrCuvAlfabet;j++)
                    aparat.getTranzitii()[i][j]=-1;
            }
            
            for (int i=0;i<nrTranz;i++){
                int x,y;
                char stare;
                x = s.nextInt();
                stare = s.next().charAt(0);
                y = s.nextInt();
                int z = aparat.pozCuvAlfabet(stare);
                if (z != -1) aparat.getTranzitii()[x][z]=y;
            }
            
            char[] cuvant = jTextField1.getText().toCharArray();
            int stareCurenta = aparat.getStareInit();
            boolean ok=true;
            for(int i=0;i<cuvant.length;i++){
                int pozLitera = aparat.pozCuvAlfabet(cuvant[i]);
                if (pozLitera != -1){
                    if(aparat.getTranzitii()[stareCurenta][pozLitera] != -1){
                        stareCurenta = aparat.getTranzitii()[stareCurenta][pozLitera];
                    }else{
                        JOptionPane.showMessageDialog(null, "Nu e bine bosule, in afara de dracului, nu am unde sa ma duc!");
                        ok = false;
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Nu e bine bosule, ai bagat o litera anapoda!");
                    ok = false;
                }
            }
            if (ok && aparat.stareFinala(stareCurenta)) JOptionPane.showMessageDialog(null, "Bravo ba, ai nimerit un cuvant!");
            else JOptionPane.showMessageDialog(null, "Ce.ai facut ma nene ma?");
            
        }catch(Exception e){
           e.printStackTrace();
           JOptionPane.showMessageDialog(null, "Eroare la deschiderea fisierului!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
